services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: BoedoClash
    volumes:
      - ./.volumes/postgres/data:/var/lib/postgresql/data/
      - ./scripts/db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "5432:5432"