CREATE TABLE usuario ( 
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    correo VARCHAR(100) UNIQUE NOT NULL,
    contraseña VARCHAR(100) NOT NULL,
    nivel INT DEFAULT 1,
    trofeos INT DEFAULT 0,
    alias VARCHAR(100) NOT NULL,
    carta_favorita VARCHAR(100)
);

CREATE TABLE cartas (
    carta_id SERIAL PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    imagen VARCHAR(255),
    calidad VARCHAR(50) NOT NULL,
    costo_elixir INT NOT NULL,
    tipo_ataque VARCHAR(50) NOT NULL,
    tipo_carta VARCHAR(50) NOT NULL,
    puntos_de_vida INT NOT NULL,
    daño INT NOT NULL,
    fuerte_contra VARCHAR(100),
    debil_contra VARCHAR(100)
);

CREATE TABLE mazos (
    mazo_id SERIAL PRIMARY KEY,
    usuario_id INT REFERENCES usuario(id) ON DELETE CASCADE,
    nombre VARCHAR(100) NOT NULL,
    promedio_elixir DECIMAL(3,2),
    victorias_totales INT DEFAULT 0
);
CREATE TABLE mazo_cartas (
    mazo_id INT REFERENCES mazos(mazo_id) ON DELETE CASCADE,
    carta_id INT REFERENCES cartas(carta_id),
    posicion INT CHECK (posicion BETWEEN 1 AND 8),
    PRIMARY KEY (mazo_id, carta_id),
    UNIQUE (mazo_id, posicion)
);
CREATE TABLE comentarios (
    comentario_id SERIAL PRIMARY KEY,
    mazo_id INT REFERENCES mazos(mazo_id) ON DELETE CASCADE,
    usuario_id INT REFERENCES usuario(id) ON DELETE SET NULL,
    texto TEXT NOT NULL,
    puntuacion INT CHECK (puntuacion >= 1 AND puntuacion <= 5)
);

INSERT INTO cartas (nombre, imagen, calidad, costo_elixir, tipo_ataque, tipo_carta, puntos_de_vida, daño)
VALUES 
('Caballero', 'https://cdn.royaleapi.com/static/img/cards/knight.png', 'comun', 3, 'terrestre', 'tropa', 1450, 160),
('Arqueras', 'https://cdn.royaleapi.com/static/img/cards/archers.png', 'comun', 3, 'mixto', 'tropa', 250, 80),
('Duendes', 'https://cdn.royaleapi.com/static/img/cards/goblins.png', 'comun', 2, 'terrestre', 'tropa', 160, 90),
('Duendes con Lanza', 'https://cdn.royaleapi.com/static/img/cards/spear-goblins.png', 'comun', 2, 'mixto', 'tropa', 110, 60),
('Esbirros', 'https://cdn.royaleapi.com/static/img/cards/minions.png', 'comun', 3, 'mixto', 'tropa', 190, 84),
('Horda de Esbirros', 'https://cdn.royaleapi.com/static/img/cards/minion-horde.png', 'comun', 5, 'mixto', 'tropa', 190, 84),
('Esqueletos', 'https://cdn.royaleapi.com/static/img/cards/skeletons.png', 'comun', 1, 'terrestre', 'tropa', 67, 67),
('Gigante', 'https://cdn.royaleapi.com/static/img/cards/giant.png', 'especial', 5, 'terrestre', 'tropa', 3300, 210),
('Montapuercos', 'https://cdn.royaleapi.com/static/img/cards/hog-rider.png', 'especial', 4, 'terrestre', 'tropa', 1400, 260),
('Mini P.E.K.K.A.', 'https://cdn.royaleapi.com/static/img/cards/mini-pekka.png', 'especial', 4, 'terrestre', 'tropa', 1100, 600),
('Valquiria', 'https://cdn.royaleapi.com/static/img/cards/valkyrie.png', 'especial', 4, 'terrestre', 'tropa', 1650, 220),
('Mosquetera', 'https://cdn.royaleapi.com/static/img/cards/musketeer.png', 'especial', 4, 'mixto', 'tropa', 600, 180),
('Bebé Dragón', 'https://cdn.royaleapi.com/static/img/cards/baby-dragon.png', 'epica', 4, 'mixto', 'tropa', 950, 130),
('Príncipe', 'https://cdn.royaleapi.com/static/img/cards/prince.png', 'epica', 5, 'terrestre', 'tropa', 1600, 320),
('Mago', 'https://cdn.royaleapi.com/static/img/cards/wizard.png', 'especial', 5, 'mixto', 'tropa', 600, 230),
('Bruja', 'https://cdn.royaleapi.com/static/img/cards/witch.png', 'epica', 5, 'mixto', 'tropa', 700, 110),
('Príncipe Oscuro', 'https://cdn.royaleapi.com/static/img/cards/dark-prince.png', 'epica', 4, 'terrestre', 'tropa', 1000, 200),
('P.E.K.K.A.', 'https://cdn.royaleapi.com/static/img/cards/pekka.png', 'epica', 7, 'terrestre', 'tropa', 3400, 670),
('Bárbaros', 'https://cdn.royaleapi.com/static/img/cards/barbarians.png', 'comun', 5, 'terrestre', 'tropa', 550, 160),
('Gigante Noble', 'https://cdn.royaleapi.com/static/img/cards/royal-giant.png', 'comun', 6, 'terrestre', 'tropa', 2500, 250),
('Bárbaros de Élite', 'https://cdn.royaleapi.com/static/img/cards/elite-barbarians.png', 'especial', 6, 'terrestre', 'tropa', 1100, 320),
('Puercos Reales', 'https://cdn.royaleapi.com/static/img/cards/royal-hogs.png', 'especial', 5, 'terrestre', 'tropa', 700, 60),
('Trío de Mosqueteras', 'https://cdn.royaleapi.com/static/img/cards/three-musketeers.png', 'especial', 9, 'mixto', 'tropa', 600, 180),
('Gólem', 'https://cdn.royaleapi.com/static/img/cards/golem.png', 'epica', 8, 'terrestre', 'tropa', 4200, 260),
('Sabueso de Lava', 'https://cdn.royaleapi.com/static/img/cards/lava-hound.png', 'legendaria', 7, 'aereo', 'tropa', 3150, 45),
('Globo Bombástico', 'https://cdn.royaleapi.com/static/img/cards/balloon.png', 'epica', 5, 'terrestre', 'tropa', 1400, 800),
('Minero', 'https://cdn.royaleapi.com/static/img/cards/miner.png', 'legendaria', 3, 'terrestre', 'tropa', 1000, 160),
('Princesa', 'https://cdn.royaleapi.com/static/img/cards/princess.png', 'legendaria', 3, 'mixto', 'tropa', 216, 140),
('Bandida', 'https://cdn.royaleapi.com/static/img/cards/bandit.png', 'legendaria', 3, 'terrestre', 'tropa', 750, 160),
('Bruja Nocturna', 'https://cdn.royaleapi.com/static/img/cards/night-witch.png', 'legendaria', 4, 'terrestre', 'tropa', 750, 260),
('Mega Caballero', 'https://cdn.royaleapi.com/static/img/cards/mega-knight.png', 'legendaria', 7, 'terrestre', 'tropa', 3300, 220),
('Montacarneros', 'https://cdn.royaleapi.com/static/img/cards/ram-rider.png', 'legendaria', 5, 'terrestre', 'tropa', 1450, 220),
('Fantasma Real', 'https://cdn.royaleapi.com/static/img/cards/royal-ghost.png', 'legendaria', 3, 'terrestre', 'tropa', 1000, 216),
('Pescador', 'https://cdn.royaleapi.com/static/img/cards/fisherman.png', 'legendaria', 3, 'terrestre', 'tropa', 720, 160),
('Arquero Mágico', 'https://cdn.royaleapi.com/static/img/cards/magic-archer.png', 'legendaria', 4, 'mixto', 'tropa', 440, 110),
('Mago de Hielo', 'https://cdn.royaleapi.com/static/img/cards/ice-wizard.png', 'legendaria', 3, 'mixto', 'tropa', 590, 75),
('Mago Eléctrico', 'https://cdn.royaleapi.com/static/img/cards/electro-wizard.png', 'legendaria', 4, 'mixto', 'tropa', 590, 93),
('Dragón Infernal', 'https://cdn.royaleapi.com/static/img/cards/inferno-dragon.png', 'legendaria', 4, 'mixto', 'tropa', 1000, 350),
('Leñador', 'https://cdn.royaleapi.com/static/img/cards/lumberjack.png', 'legendaria', 4, 'terrestre', 'tropa', 1060, 200),
('Chispitas', 'https://cdn.royaleapi.com/static/img/cards/sparky.png', 'legendaria', 6, 'terrestre', 'tropa', 1200, 1100),
('Bruja Madre', 'https://cdn.royaleapi.com/static/img/cards/mother-witch.png', 'legendaria', 4, 'mixto', 'tropa', 560, 110),
('Ejército de Esqueletos', 'https://cdn.royaleapi.com/static/img/cards/skeleton-army.png', 'epica', 3, 'terrestre', 'tropa', 67, 67),
('Guardias', 'https://cdn.royaleapi.com/static/img/cards/guards.png', 'epica', 3, 'terrestre', 'tropa', 200, 100),
('Lanzarrocas', 'https://cdn.royaleapi.com/static/img/cards/bowler.png', 'epica', 5, 'terrestre', 'tropa', 1600, 240),
('Verdugo', 'https://cdn.royaleapi.com/static/img/cards/executioner.png', 'epica', 5, 'mixto', 'tropa', 1000, 140),
('Esqueleto Gigante', 'https://cdn.royaleapi.com/static/img/cards/giant-skeleton.png', 'epica', 6, 'terrestre', 'tropa', 3000, 170),
('Cazador', 'https://cdn.royaleapi.com/static/img/cards/hunter.png', 'epica', 4, 'mixto', 'tropa', 700, 70),
('Carro Cañón', 'https://cdn.royaleapi.com/static/img/cards/cannon-cart.png', 'epica', 5, 'terrestre', 'tropa', 700, 170),
('Ariete de Batalla', 'https://cdn.royaleapi.com/static/img/cards/battle-ram.png', 'especial', 4, 'terrestre', 'tropa', 750, 250),
('Lanzafuegos', 'https://cdn.royaleapi.com/static/img/cards/firecracker.png', 'comun', 3, 'mixto', 'tropa', 250, 50),
('Espíritu de Hielo', 'https://cdn.royaleapi.com/static/img/cards/ice-spirit.png', 'comun', 1, 'mixto', 'tropa', 190, 90),
('Espíritu Ígneo', 'https://cdn.royaleapi.com/static/img/cards/fire-spirit.png', 'comun', 1, 'mixto', 'tropa', 190, 150),
('Barril de Esqueletos', 'https://cdn.royaleapi.com/static/img/cards/skeleton-barrel.png', 'comun', 3, 'terrestre', 'tropa', 440, 0),
('Pandilla de Duendes', 'https://cdn.royaleapi.com/static/img/cards/goblin-gang.png', 'comun', 3, 'mixto', 'tropa', 160, 90),
('Duende Lanzadardos', 'https://cdn.royaleapi.com/static/img/cards/dart-goblin.png', 'especial', 3, 'mixto', 'tropa', 216, 100),
('Megaesbirro', 'https://cdn.royaleapi.com/static/img/cards/mega-minion.png', 'especial', 3, 'mixto', 'tropa', 700, 260),
('Máquina Voladora', 'https://cdn.royaleapi.com/static/img/cards/flying-machine.png', 'especial', 4, 'mixto', 'tropa', 500, 140),
('Reclutas Reales', 'https://cdn.royaleapi.com/static/img/cards/royal-recruits.png', 'comun', 7, 'terrestre', 'tropa', 500, 110),
('Dragón Eléctrico', 'https://cdn.royaleapi.com/static/img/cards/electro-dragon.png', 'epica', 5, 'mixto', 'tropa', 800, 160),
('Reina Arquera', 'https://cdn.royaleapi.com/static/img/cards/archer-queen.png', 'campeon', 5, 'mixto', 'tropa', 1000, 225),
('Caballero Dorado', 'https://cdn.royaleapi.com/static/img/cards/golden-knight.png', 'campeon', 4, 'terrestre', 'tropa', 1800, 160),
('Rey Esqueleto', 'https://cdn.royaleapi.com/static/img/cards/skeleton-king.png', 'campeon', 5, 'terrestre', 'tropa', 2300, 180),
('Monje', 'https://cdn.royaleapi.com/static/img/cards/monk.png', 'campeon', 5, 'mixto', 'tropa', 2000, 150),
('Gran Minero', 'https://cdn.royaleapi.com/static/img/cards/mighty-miner.png', 'campeon', 4, 'terrestre', 'tropa', 2400, 400),
('Goblinstein', 'https://cdn.royaleapi.com/static/img/cards/goblinstein.png', 'legendaria', 5, 'mixto', 'tropa', 2000, 140),
('Máquina de Duendes', 'https://cdn.royaleapi.com/static/img/cards/goblin-machine.png', 'legendaria', 5, 'terrestre', 'tropa', 2200, 180),
('Duende Demoledor', 'https://cdn.royaleapi.com/static/img/cards/goblin-demolisher.png', 'epica', 4, 'terrestre', 'tropa', 1000, 150),
('Bandida Líder', 'https://cdn.royaleapi.com/static/img/cards/boss-bandit.png', 'campeon', 6, 'terrestre', 'tropa', 2500, 200),
('Barril de Duendes', 'https://cdn.royaleapi.com/static/img/cards/goblin-barrel.png', 'epica', 3, 'hechizo', 'hechizo', 0, 0),
('Cementerio', 'https://cdn.royaleapi.com/static/img/cards/graveyard.png', 'legendaria', 5, 'hechizo', 'hechizo', 0, 0),
('Congelar', 'https://cdn.royaleapi.com/static/img/cards/freeze.png', 'epica', 4, 'hechizo', 'hechizo', 0, 0),
('Bola de Fuego', 'https://cdn.royaleapi.com/static/img/cards/fireball.png', 'especial', 4, 'hechizo', 'hechizo', 0, 570),
('Descarga', 'https://cdn.royaleapi.com/static/img/cards/zap.png', 'comun', 2, 'hechizo', 'hechizo', 0, 160),
('Flechas', 'https://cdn.royaleapi.com/static/img/cards/arrows.png', 'comun', 3, 'hechizo', 'hechizo', 0, 300),
('Cohete', 'https://cdn.royaleapi.com/static/img/cards/rocket.png', 'epica', 6, 'hechizo', 'hechizo', 0, 1200),
('Rayo', 'https://cdn.royaleapi.com/static/img/cards/lightning.png', 'epica', 6, 'hechizo', 'hechizo', 0, 800),
('Veneno', 'https://cdn.royaleapi.com/static/img/cards/poison.png', 'epica', 4, 'hechizo', 'hechizo', 0, 600),
('Tornado', 'https://cdn.royaleapi.com/static/img/cards/tornado.png', 'epica', 3, 'hechizo', 'hechizo', 0, 0),
('Clon', 'https://cdn.royaleapi.com/static/img/cards/clone.png', 'epica', 3, 'hechizo', 'hechizo', 0, 0),
('Espejo', 'https://cdn.royaleapi.com/static/img/cards/mirror.png', 'epica', 0, 'hechizo', 'hechizo', 0, 0),
('Furia', 'https://cdn.royaleapi.com/static/img/cards/rage.png', 'epica', 2, 'hechizo', 'hechizo', 0, 0),
('Barril de Bárbaro', 'https://cdn.royaleapi.com/static/img/cards/barbarian-barrel.png', 'epica', 2, 'hechizo', 'hechizo', 0, 200),
('Terremoto', 'https://cdn.royaleapi.com/static/img/cards/earthquake.png', 'especial', 3, 'hechizo', 'hechizo', 0, 200),
('Cañón', 'https://cdn.royaleapi.com/static/img/cards/cannon.png', 'comun', 3, 'terrestre', 'estructura', 740, 180),
('Mortero', 'https://cdn.royaleapi.com/static/img/cards/mortar.png', 'comun', 4, 'terrestre', 'estructura', 1200, 230),
('Torre Infernal', 'https://cdn.royaleapi.com/static/img/cards/inferno-tower.png', 'especial', 5, 'mixto', 'estructura', 1450, 1000),
('Torre Bombardera', 'https://cdn.royaleapi.com/static/img/cards/bomb-tower.png', 'especial', 4, 'terrestre', 'estructura', 1100, 180),
('Choza Bárbara', 'https://cdn.royaleapi.com/static/img/cards/barbarian-hut.png', 'especial', 7, 'terrestre', 'estructura', 1100, 0),
('Recolector de Elixir', 'https://cdn.royaleapi.com/static/img/cards/elixir-collector.png', 'especial', 6, 'n/a', 'estructura', 900, 0),
('Horno', 'https://cdn.royaleapi.com/static/img/cards/furnace.png', 'especial', 4, 'terrestre', 'estructura', 850, 0),
('Choza de Duendes', 'https://cdn.royaleapi.com/static/img/cards/goblin-hut.png', 'especial', 5, 'mixto', 'estructura', 800, 0),
('Lápida', 'https://cdn.royaleapi.com/static/img/cards/tombstone.png', 'especial', 3, 'terrestre', 'estructura', 440, 0),
('Torre Tesla', 'https://cdn.royaleapi.com/static/img/cards/tesla.png', 'especial', 4, 'mixto', 'estructura', 950, 190),
('Ballesta', 'https://cdn.royaleapi.com/static/img/cards/x-bow.png', 'epica', 6, 'mixto', 'estructura', 1380, 30),
('Excavadora de Duendes', 'https://cdn.royaleapi.com/static/img/cards/goblin-drill.png', 'epica', 4, 'terrestre', 'estructura', 950, 0),
('Arbusto Sospechoso', 'https://cdn.royaleapi.com/static/img/cards/suspicious-bush.png', 'especial', 2, 'terrestre', 'estructura', 400, 100);
